### ISSUE TITLE
Arenavision AGENDA

### ISSUE THREAD

**Issue by giomas89** [manuelsousa7/p2p-streams-parsers#2]
Hello
For some time is no longer available, the agenda/schedule of Arenavision
Any solution?

**Comment by manuelsousa7** [comment]
Thank you for reporting this bug, I will try to look into it as soon as I can.

**Comment by manuelsousa7** [comment]
Unfortunately, arenavision website suffered some code restructure, and the parser stop working. Some things need to be rethought to adapt the parser to this new structure. I am afraid it will take some days/weeks to get it fixed.

**Comment by giomas89** [comment]
No problem ;-)
I was glad to report bugs
It is always a great job :)

**Comment by manuelsousa7** [comment]
Unfortunately this project is deprecated
